// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuneBridge.Core.Infrastructure.Context;

#nullable disable

namespace TuneBridge.Core.Infrastructure.Migrations
{
    [DbContext(typeof(MediaLinkCacheDbContext))]
    [Migration("20251118155609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TuneBridge.Core.Infrastructure.Entity.MediaLinkCacheEntry", b =>
                {
                    b.Property<string>("Rkey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLookedUpAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Rkey");

                    b.HasIndex("LastLookedUpAt");

                    b.HasIndex("RecordUri")
                        .IsUnique();

                    b.ToTable("CacheEntries");
                });

            modelBuilder.Entity("TuneBridge.Core.Infrastructure.Entity.MediaLookupEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAlbum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LookupType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LookupValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaLinkCacheEntryRkey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaLinkCacheEntryRkey");

                    b.HasIndex("LookupValue", "LookupType", "IsAlbum")
                        .IsUnique();

                    b.ToTable("LookupEntries");
                });

            modelBuilder.Entity("TuneBridge.Core.Infrastructure.Entity.MediaLookupEntry", b =>
                {
                    b.HasOne("TuneBridge.Core.Infrastructure.Entity.MediaLinkCacheEntry", "MediaLinkCacheEntry")
                        .WithMany("LookupEntries")
                        .HasForeignKey("MediaLinkCacheEntryRkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaLinkCacheEntry");
                });

            modelBuilder.Entity("TuneBridge.Core.Infrastructure.Entity.MediaLinkCacheEntry", b =>
                {
                    b.Navigation("LookupEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
