<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BridgeBeats.Worker.Tidal</RootNamespace>
    <UserSecretsId>bridgebeats-apphost</UserSecretsId>
    <RepositoryUrl>https://github.com/tsmarvin/BridgeBeats</RepositoryUrl>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>embedded</DebugType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BridgeBeats.Core\BridgeBeats.Core.csproj" />
  </ItemGroup>

</Project>
