// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuneBridge.Domain.Implementations.Database;

#nullable disable

namespace TuneBridge.Migrations.MediaLinkCache
{
    [DbContext(typeof(MediaLinkCacheDbContext))]
    partial class MediaLinkCacheDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("TuneBridge.Domain.Contracts.Entities.InputLinkEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaLinkCacheEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.HasIndex("MediaLinkCacheEntryId");

                    b.ToTable("InputLinks");
                });

            modelBuilder.Entity("TuneBridge.Domain.Contracts.Entities.MediaLinkCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLookedUpAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastLookedUpAt");

                    b.HasIndex("RecordUri")
                        .IsUnique();

                    b.ToTable("CacheEntries");
                });

            modelBuilder.Entity("TuneBridge.Domain.Contracts.Entities.InputLinkEntry", b =>
                {
                    b.HasOne("TuneBridge.Domain.Contracts.Entities.MediaLinkCacheEntry", "MediaLinkCacheEntry")
                        .WithMany("InputLinks")
                        .HasForeignKey("MediaLinkCacheEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaLinkCacheEntry");
                });

            modelBuilder.Entity("TuneBridge.Domain.Contracts.Entities.MediaLinkCacheEntry", b =>
                {
                    b.Navigation("InputLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
