// <auto-generated />
using System;
using BridgeBeats.Domain.Implementations.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BridgeBeats.Migrations
{
    [DbContext(typeof(MediaLinkCacheDbContext))]
    [Migration("20251208011842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BridgeBeats.Domain.Contracts.Entities.MediaLinkCacheEntry", b =>
                {
                    b.Property<string>("Rkey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLookedUpAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Rkey");

                    b.HasIndex("CardId");

                    b.HasIndex("LastLookedUpAt");

                    b.HasIndex("RecordUri")
                        .IsUnique();

                    b.ToTable("CacheEntries");
                });

            modelBuilder.Entity("BridgeBeats.Domain.Contracts.Entities.MediaLookupEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAlbum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LookupType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LookupValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaLinkCacheEntryRkey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaLinkCacheEntryRkey");

                    b.HasIndex("LookupValue", "LookupType", "IsAlbum")
                        .IsUnique();

                    b.ToTable("LookupEntries");
                });

            modelBuilder.Entity("BridgeBeats.Domain.Contracts.Entities.MediaProviderEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaLinkCacheEntryRkey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaLinkCacheEntryRkey");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Provider", "ProviderId")
                        .IsUnique();

                    b.ToTable("ProviderEntries");
                });

            modelBuilder.Entity("BridgeBeats.Domain.Contracts.Entities.MediaLookupEntry", b =>
                {
                    b.HasOne("BridgeBeats.Domain.Contracts.Entities.MediaLinkCacheEntry", "MediaLinkCacheEntry")
                        .WithMany("LookupEntries")
                        .HasForeignKey("MediaLinkCacheEntryRkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaLinkCacheEntry");
                });

            modelBuilder.Entity("BridgeBeats.Domain.Contracts.Entities.MediaProviderEntry", b =>
                {
                    b.HasOne("BridgeBeats.Domain.Contracts.Entities.MediaLinkCacheEntry", "MediaLinkCacheEntry")
                        .WithMany("ProviderEntries")
                        .HasForeignKey("MediaLinkCacheEntryRkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaLinkCacheEntry");
                });

            modelBuilder.Entity("BridgeBeats.Domain.Contracts.Entities.MediaLinkCacheEntry", b =>
                {
                    b.Navigation("LookupEntries");

                    b.Navigation("ProviderEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
