<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Version>0.0.1</Version>
    <StartupObject>BridgeBeats.Web.Program</StartupObject>
    <Authors>Taylor Marvin</Authors>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DebugType>embedded</DebugType>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <RuntimeIdentifiers>win-x64;win-arm64;linux-x64;linux-arm64;osx-arm64</RuntimeIdentifiers>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <UserSecretsId>bridgebeats-apphost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Authentication.ApiKey" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.2.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.15.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.3.0" />
    <PackageReference Include="NetCord" Version="1.0.0-alpha.455" />
    <PackageReference Include="NetCord.Hosting" Version="1.0.0-alpha.455" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BridgeBeats.ServiceDefaults\BridgeBeats.ServiceDefaults.csproj" />
    <ProjectReference Include="..\BridgeBeats.Contracts\BridgeBeats.Contracts.csproj" />
    <ProjectReference Include="..\BridgeBeats.Infrastructure\BridgeBeats.Infrastructure.csproj" />
    <ProjectReference Include="..\BridgeBeats.Providers\BridgeBeats.Providers.csproj" />
    <ProjectReference Include="..\BridgeBeats.Services\BridgeBeats.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BridgeBeats.Tests" />
  </ItemGroup>

</Project>
