// <auto-generated />
using System;
using BridgeBeats.Core.Infrastructure.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BridgeBeats.Core.Infrastructure.Migrations {
    [DbContext( typeof( ApplicationDbContext ) )]
    [Migration( "20260607055439_UniqueEmailIndex" )]
    partial class UniqueEmailIndex {
        /// <inheritdoc />
        protected override void BuildTargetModel( ModelBuilder modelBuilder ) {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation( "ProductVersion", "10.0.8" );

            modelBuilder.Entity( "BridgeBeats.Core.Infrastructure.Identity.ApplicationUser", b => {
                b.Property<string>( "Id" )
                    .HasColumnType( "TEXT" );

                b.Property<int>( "AccessFailedCount" )
                    .HasColumnType( "INTEGER" );

                b.Property<string>( "ApiKeyHash" )
                    .HasColumnType( "TEXT" );

                b.Property<DateTime?>( "AppleMusicTokenExpiration" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "AppleMusicUserToken" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "AtProtoAccessToken" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "AtProtoDPoPKey" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "AtProtoDid" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "AtProtoHandle" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "AtProtoRefreshToken" )
                    .HasColumnType( "TEXT" );

                b.Property<DateTime?>( "AtProtoTokenExpiration" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "ConcurrencyStamp" )
                    .IsConcurrencyToken( )
                    .HasColumnType( "TEXT" );

                b.Property<DateTime>( "CreatedAt" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "Email" )
                    .HasMaxLength( 256 )
                    .HasColumnType( "TEXT" );

                b.Property<bool>( "EmailConfirmed" )
                    .HasColumnType( "INTEGER" );

                b.Property<bool>( "LockoutEnabled" )
                    .HasColumnType( "INTEGER" );

                b.Property<DateTimeOffset?>( "LockoutEnd" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "NormalizedEmail" )
                    .HasMaxLength( 256 )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "NormalizedUserName" )
                    .HasMaxLength( 256 )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "PasswordHash" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "PhoneNumber" )
                    .HasColumnType( "TEXT" );

                b.Property<bool>( "PhoneNumberConfirmed" )
                    .HasColumnType( "INTEGER" );

                b.Property<DateTime?>( "RateLimitWindowStart" )
                    .HasColumnType( "TEXT" );

                b.Property<int>( "RequestCount" )
                    .HasColumnType( "INTEGER" );

                b.Property<string>( "SecurityStamp" )
                    .HasColumnType( "TEXT" );

                b.Property<bool>( "TwoFactorEnabled" )
                    .HasColumnType( "INTEGER" );

                b.Property<string>( "UserName" )
                    .HasMaxLength( 256 )
                    .HasColumnType( "TEXT" );

                b.HasKey( "Id" );

                b.HasIndex( "ApiKeyHash" )
                    .IsUnique( );

                b.HasIndex( "AtProtoDid" )
                    .IsUnique( )
                    .HasFilter( "[AtProtoDid] IS NOT NULL" );

                b.HasIndex( "NormalizedEmail" )
                    .IsUnique( )
                    .HasDatabaseName( "EmailIndex" );

                b.HasIndex( "NormalizedUserName" )
                    .IsUnique( )
                    .HasDatabaseName( "UserNameIndex" );

                b.ToTable( "AspNetUsers", (string)null );
            } );

            modelBuilder.Entity( "BridgeBeats.Core.Infrastructure.Identity.AtProtoOAuthState", b => {
                b.Property<string>( "State" )
                    .HasMaxLength( 128 )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "AuthorizationServerUri" )
                    .HasMaxLength( 512 )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "CodeVerifier" )
                    .IsRequired( )
                    .HasMaxLength( 512 )
                    .HasColumnType( "TEXT" );

                b.Property<DateTime>( "CreatedAt" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "DPoPKeyJwk" )
                    .IsRequired( )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "Did" )
                    .HasMaxLength( 128 )
                    .HasColumnType( "TEXT" );

                b.Property<DateTime>( "ExpiresAt" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "Handle" )
                    .IsRequired( )
                    .HasMaxLength( 256 )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "PdsUri" )
                    .HasMaxLength( 512 )
                    .HasColumnType( "TEXT" );

                b.HasKey( "State" );

                b.HasIndex( "ExpiresAt" );

                b.ToTable( "AtProtoOAuthStates" );
            } );

            modelBuilder.Entity( "BridgeBeats.Core.Infrastructure.Playlists.PlaylistEntry", b => {
                b.Property<string>( "PlaylistId" )
                    .HasMaxLength( 64 )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "CardIds" )
                    .IsRequired( )
                    .HasMaxLength( 2000 )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "CardRkeys" )
                    .IsRequired( )
                    .HasMaxLength( 2000 )
                    .HasColumnType( "TEXT" );

                b.Property<DateTime>( "CreatedAt" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "Description" )
                    .HasMaxLength( 1000 )
                    .HasColumnType( "TEXT" );

                b.Property<DateTime?>( "ExpiresAt" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "Title" )
                    .HasMaxLength( 200 )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "UserId" )
                    .HasMaxLength( 450 )
                    .HasColumnType( "TEXT" );

                b.HasKey( "PlaylistId" );

                b.HasIndex( "CreatedAt" );

                b.HasIndex( "ExpiresAt" );

                b.HasIndex( "UserId" );

                b.ToTable( "Playlists" );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityRole", b => {
                b.Property<string>( "Id" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "ConcurrencyStamp" )
                    .IsConcurrencyToken( )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "Name" )
                    .HasMaxLength( 256 )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "NormalizedName" )
                    .HasMaxLength( 256 )
                    .HasColumnType( "TEXT" );

                b.HasKey( "Id" );

                b.HasIndex( "NormalizedName" )
                    .IsUnique( )
                    .HasDatabaseName( "RoleNameIndex" );

                b.ToTable( "AspNetRoles", (string)null );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b => {
                b.Property<int>( "Id" )
                    .ValueGeneratedOnAdd( )
                    .HasColumnType( "INTEGER" );

                b.Property<string>( "ClaimType" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "ClaimValue" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "RoleId" )
                    .IsRequired( )
                    .HasColumnType( "TEXT" );

                b.HasKey( "Id" );

                b.HasIndex( "RoleId" );

                b.ToTable( "AspNetRoleClaims", (string)null );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b => {
                b.Property<int>( "Id" )
                    .ValueGeneratedOnAdd( )
                    .HasColumnType( "INTEGER" );

                b.Property<string>( "ClaimType" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "ClaimValue" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "UserId" )
                    .IsRequired( )
                    .HasColumnType( "TEXT" );

                b.HasKey( "Id" );

                b.HasIndex( "UserId" );

                b.ToTable( "AspNetUserClaims", (string)null );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b => {
                b.Property<string>( "LoginProvider" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "ProviderKey" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "ProviderDisplayName" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "UserId" )
                    .IsRequired( )
                    .HasColumnType( "TEXT" );

                b.HasKey( "LoginProvider", "ProviderKey" );

                b.HasIndex( "UserId" );

                b.ToTable( "AspNetUserLogins", (string)null );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b => {
                b.Property<string>( "UserId" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "RoleId" )
                    .HasColumnType( "TEXT" );

                b.HasKey( "UserId", "RoleId" );

                b.HasIndex( "RoleId" );

                b.ToTable( "AspNetUserRoles", (string)null );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b => {
                b.Property<string>( "UserId" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "LoginProvider" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "Name" )
                    .HasColumnType( "TEXT" );

                b.Property<string>( "Value" )
                    .HasColumnType( "TEXT" );

                b.HasKey( "UserId", "LoginProvider", "Name" );

                b.ToTable( "AspNetUserTokens", (string)null );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b => {
                b.HasOne( "Microsoft.AspNetCore.Identity.IdentityRole", null )
                    .WithMany( )
                    .HasForeignKey( "RoleId" )
                    .OnDelete( DeleteBehavior.Cascade )
                    .IsRequired( );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b => {
                b.HasOne( "BridgeBeats.Core.Infrastructure.Identity.ApplicationUser", null )
                    .WithMany( )
                    .HasForeignKey( "UserId" )
                    .OnDelete( DeleteBehavior.Cascade )
                    .IsRequired( );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b => {
                b.HasOne( "BridgeBeats.Core.Infrastructure.Identity.ApplicationUser", null )
                    .WithMany( )
                    .HasForeignKey( "UserId" )
                    .OnDelete( DeleteBehavior.Cascade )
                    .IsRequired( );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b => {
                b.HasOne( "Microsoft.AspNetCore.Identity.IdentityRole", null )
                    .WithMany( )
                    .HasForeignKey( "RoleId" )
                    .OnDelete( DeleteBehavior.Cascade )
                    .IsRequired( );

                b.HasOne( "BridgeBeats.Core.Infrastructure.Identity.ApplicationUser", null )
                    .WithMany( )
                    .HasForeignKey( "UserId" )
                    .OnDelete( DeleteBehavior.Cascade )
                    .IsRequired( );
            } );

            modelBuilder.Entity( "Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b => {
                b.HasOne( "BridgeBeats.Core.Infrastructure.Identity.ApplicationUser", null )
                    .WithMany( )
                    .HasForeignKey( "UserId" )
                    .OnDelete( DeleteBehavior.Cascade )
                    .IsRequired( );
            } );
#pragma warning restore 612, 618
        }
    }
}
